### ISSUE TITLE
I just downlaod this and running it on the latest getting Java Error

### ISSUE THREAD

**Issue by subtubes-io** [danyg/jsdoc3Template#3]
Here is the output kinda length and some of it I know is just the console output 
the following directories are created but none of the documentation files are generated (NO HTML)
/img
/js
/styles

also I noticed the template folder needs to be called myCustom 
anyways thanks for looking at this.  I will also look and see if I can debug it myself but I might not have tome for a few day. 

C:\jsdoc3\jsdoc.cmd C:\Zend2\Apache2\htdocs\OOSS\wellness-plugins\src -r -d C:\Zend2\Apache2\htdocs\OOSS\wellness-plugins_docs -t C:\jsdoc3\templates\myCustom
Init myPublisher
[DEBUG]  ## REMOVE OVER DATA ##
[DEBUG]  removing undocumented data
[DEBUG]  DONE!
[DEBUG]  removing ignored doclets
[DEBUG]  DONE!
[DEBUG]  removing private doclets
[DEBUG]  DONE!
[DEBUG]  removing <anonymous> doclets
[DEBUG]  [debug] removed <anonymous> doclets
[DEBUG]  ## DONE!
[DEBUG]  ## processPackageInfo ##
[ERROR]  Cannot parse package.json: java.io.FileNotFoundException: File not found: C:\Zend2\Apache2\htdocs\OOSS\wellness-plugins\src../package.json
[DEBUG]  ## DONE!
[DEBUG]  ## _processLicense ##
[DEBUG]  ## DONE!
[DEBUG]  ## _processReadme ##
[DEBUG]  ## DONE!
[DEBUG]  ## _processData AND register Links ##
[DEBUG]  processData| Items a iterar:  6
[DEBUG]  processData| Iterados: 0/6
[DEBUG]  processData| Iterados: 1/6
[DEBUG]  processData| Iterados: 2/6
[DEBUG]  processData| Iterados: 3/6
[DEBUG]  processData| Iterados: 4/6
[DEBUG]  processData| Iterados: 5/6
[DEBUG]  ## DONE!
[DEBUG]  ## _createOutDir ##
[DEBUG]  created output dir  C:\Zend2\Apache2\htdocs\OOSS\wellness-plugins_docs
[DEBUG]  ## DONE!
[DEBUG]  ## copying static files to output dir
[DEBUG]  ## DONE!
[DEBUG]  ## orderData
[DEBUG]  ## DONE!
[DEBUG]  ## buildSearchIndex
[DEBUG]  -- building global index (0 items)
[DEBUG]  -- building file index (0 items)
[DEBUG]  -- building external index (0 items)
[DEBUG]  -- building constant index (0 items)
[DEBUG]  -- building function index (1 items)
[DEBUG]  -- building event index (0 items)
[DEBUG]  -- building mixin index (0 items)
[DEBUG]  -- building class index (4 items)
[DEBUG]  -- building namespace index (0 items)
[DEBUG]  -- building module index (0 items)
[DEBUG]  -- building interface index (0 items)
[DEBUG]  ## DONE!
[DEBUG]  ## genFilesPages
C:/jsdoc3/logs/methods-2.log
org.mozilla.javascript.WrappedException: Wrapped java.io.IOException: The system cannot find the path specified
    at org.mozilla.javascript.Context.throwAsScriptRuntimeEx(Context.java:1786)
    at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:183)
    at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:247)
    at org.mozilla.javascript.optimizer.OptRuntime.callProp0(OptRuntime.java:119)
    at org.mozilla.javascript.gen.file__C__jsdoc3_templates_myCustom_inc_processFiles_js_38._c_anonymous_1(Unknown Source)
    at org.mozilla.javascript.gen.file__C__jsdoc3_templates_myCustom_inc_processFiles_js_38.call(Unknown Source)
    at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:66)
    at org.mozilla.javascript.gen.file__C__jsdoc3_templates_myCustom_inc_processFiles_js_38._c_anonymous_2(Unknown Source)
    at org.mozilla.javascript.gen.file__C__jsdoc3_templates_myCustom_inc_processFiles_js_38.call(Unknown Source)
    at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:66)
    at org.mozilla.javascript.gen.file__C__jsdoc3_templates_myCustom_inc_myPublisher_js_31._c_anonymous_23(Unknown Source)
    at org.mozilla.javascript.gen.file__C__jsdoc3_templates_myCustom_inc_myPublisher_js_31.call(Unknown Source)
    at org.mozilla.javascript.optimizer.OptRuntime.callProp0(OptRuntime.java:119)
    at org.mozilla.javascript.gen.file__C__jsdoc3_templates_myCustom_inc_myPublisher_js_31._c_anonymous_1(Unknown Source)
    at org.mozilla.javascript.gen.file__C__jsdoc3_templates_myCustom_inc_myPublisher_js_31.call(Unknown Source)
    at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:76)
    at org.mozilla.javascript.gen.file__C__jsdoc3_templates_myCustom__publish_js_30._c_anonymous_1(Unknown Source)
    at org.mozilla.javascript.gen.file__C__jsdoc3_templates_myCustom__publish_js_30.call(Unknown Source)
    at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:86)
    at org.mozilla.javascript.gen.C__jsdoc3_jsdoc_js_1._c_main_9(Unknown Source)
    at org.mozilla.javascript.gen.C__jsdoc3_jsdoc_js_1.call(Unknown Source)
    at org.mozilla.javascript.optimizer.OptRuntime.callName0(OptRuntime.java:108)
    at org.mozilla.javascript.gen.C__jsdoc3_jsdoc_js_1._c_script_0(Unknown Source)
    at org.mozilla.javascript.gen.C__jsdoc3_jsdoc_js_1.call(Unknown Source)
    at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:426)
    at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3178)
    at org.mozilla.javascript.gen.C__jsdoc3_jsdoc_js_1.call(Unknown Source)
    at org.mozilla.javascript.gen.C__jsdoc3_jsdoc_js_1.exec(Unknown Source)
    at org.mozilla.javascript.tools.shell.Main.evaluateScript(Main.java:654)
    at org.mozilla.javascript.tools.shell.Main.processFileSecure(Main.java:552)
    at org.mozilla.javascript.tools.shell.Main.processFile(Main.java:507)
    at org.mozilla.javascript.tools.shell.Main.processSource(Main.java:499)
    at org.mozilla.javascript.tools.shell.Main.processFiles(Main.java:215)
    at org.mozilla.javascript.tools.shell.Main$IProxy.run(Main.java:134)
    at org.mozilla.javascript.Context.call(Context.java:521)
    at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:535)
    at org.mozilla.javascript.tools.shell.Main.exec(Main.java:198)
    at org.mozilla.javascript.tools.shell.Main.main(Main.java:174)
Caused by: java.io.IOException: The system cannot find the path specified
    at java.io.WinNTFileSystem.createFileExclusively(Native Method)
    at java.io.File.createNewFile(Unknown Source)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:161)
    ... 36 more

**Comment by danyg** [comment]
Try making a C:\jsdoc3\logs directory
Any way I fix that in futher commits

**Comment by danyg** [comment]
In the README.md you can see a Usage example code. All directories in the bash must be created before launch jsdoc3 (I'm sorry for that)

**Comment by subtubes-io** [comment]
Any chance you can just add the files to the template? Not sure if the basj will work on win-bash I am on windows you see :(
