### ISSUE TITLE
missing modules?

### ISSUE THREAD

**Issue by eddyystop** [danyg/jsdoc3Template#4]
Edit: Summary of comments is:
1. So I downloaded commit 8bc33541 of Jsdoc3 which is the last commit before changes started to be made for the Node port (+1) including some Taffy changes.
2. So I hacked rhino_modules/fs.js about line 8 adding
filename = filename.replace(/../g, '');   // certainly better ways to handle this
3. Put in your input folder
package.json from ./
LICENSE from ./LICENSE.MD though any file will do.
README with some junk.
4. Where I'm at is files in ./templates/myCustom/static are 0kb. I need searchdoc.js to start with.

++++++++++++++++

I installed the template as template/myCustom under the latest version of jsdoc3.

It fails while running because these 2 modules can't be found:

/**
- @module jsdoc/util/templateHelper
  */

var hash = require('pajhome/hash');
var dictionary = require('jsdoc/tag/dictionary');

What should I do?

**Comment by eddyystop** [comment]
require('jsdoc/tag/dictionary'); is where it should be.

I created rhino_modules/pajhome/hash.js by copying http://pajhome.org.uk/crypt/md5/md5.html to the file and adding
exports.hex_md5 = hex_md5;

Now I get  the following on Win7 (this includes some console.log's I threw in). This may result from this.data.remove in _removeOverData being undefined, as is this.data.get. So I may be missing a dependency to taffyDb..

E:\wwwroot\jsdoc3>jsdoc -t templates/myCustom -r ./tmp
Init myPublisher
.. calling myPublisher.publish(data, opts)
<Function>
{
    "destination": "./out/",
    "_": [
        "./tmp"
    ],
    "template": "E:\wwwroot\jsdoc3\templates\myCustom",
    "recurse": true
}
myPublisher.publish entered. call _initVars
entered _initVars
underscore at > templates/myCustom/lib/underscore/underscore.js
templates at > templates/myCustom/lib/underscore/template.js
fs
templateHelper
requiring dictionary
requiring hash
required hash successfully
processFiles
processTags
calling getProcessable Tags
processPropewrties
calling getProcessableProps
end of _initVars
calling _loadTemplates
dbg msg > ## REMOVE OVER DATA ##
{
    "0": "[DEBUG] ",
    "1": "## REMOVE OVER DATA ##"
}
dbg msg > removing undocumented data
{
    "0": "[DEBUG] ",
    "1": "removing undocumented data"
}
org.mozilla.javascript.EcmaError: TypeError: Cannot find function remove in obje
ct
function () {...}.
        at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.jav
a:3785)
        at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.jav
a:3763)
        at org.mozilla.javascript.ScriptRuntime.typeError(ScriptRuntime.java:379
1)
        at org.mozilla.javascript.ScriptRuntime.typeError2(ScriptRuntime.java:38
10)
        at org.mozilla.javascript.ScriptRuntime.notFunctionError(ScriptRuntime.j
ava:3881)
        at org.mozilla.javascript.ScriptRuntime.getPropFunctionAndThisHelper(Scr
iptRuntime.java:2360)
        at org.mozilla.javascript.ScriptRuntime.getPropFunctionAndThis(ScriptRun
time.java:2327)
        at org.mozilla.javascript.gen.file__E__wwwroot_jsdoc3_templates_myCustom
_inc_myPublisher_js_32._c_anonymous_4(Unknown Source)
        at org.mozilla.javascript.gen.file__E__wwwroot_jsdoc3_templates_myCustom
_inc_myPublisher_js_32.call(Unknown Source)
        at org.mozilla.javascript.optimizer.OptRuntime.callProp0(OptRuntime.java
:119)
        at org.mozilla.javascript.gen.file__E__wwwroot_jsdoc3_templates_myCustom
_inc_myPublisher_js_32._c_anonymous_1(Unknown Source)
        at org.mozilla.javascript.gen.file__E__wwwroot_jsdoc3_templates_myCustom
_inc_myPublisher_js_32.call(Unknown Source)
        at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:76)

```
    at org.mozilla.javascript.gen.file__E__wwwroot_jsdoc3_templates_myCustom
```

_publish_js_31._c_anonymous_1(Unknown Source)
        at org.mozilla.javascript.gen.file__E__wwwroot_jsdoc3_templates_myCustom
_publish_js_31.call(Unknown Source)
        at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:86)

```
    at org.mozilla.javascript.gen.E__wwwroot_jsdoc3_jsdoc_js_1._c_main_8(Unk
```

nown Source)
        at org.mozilla.javascript.gen.E__wwwroot_jsdoc3_jsdoc_js_1.call(Unknown
Source)
        at org.mozilla.javascript.optimizer.OptRuntime.callName0(OptRuntime.java
:108)
        at org.mozilla.javascript.gen.E__wwwroot_jsdoc3_jsdoc_js_1._c_script_0(U
nknown Source)
        at org.mozilla.javascript.gen.E__wwwroot_jsdoc3_jsdoc_js_1.call(Unknown
Source)
        at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:4
26)
        at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:317
8)
        at org.mozilla.javascript.gen.E__wwwroot_jsdoc3_jsdoc_js_1.call(Unknown
Source)
        at org.mozilla.javascript.gen.E__wwwroot_jsdoc3_jsdoc_js_1.exec(Unknown
Source)
        at org.mozilla.javascript.tools.shell.Main.evaluateScript(Main.java:654)

```
    at org.mozilla.javascript.tools.shell.Main.processFileSecure(Main.java:5
```

52)
        at org.mozilla.javascript.tools.shell.Main.processFile(Main.java:507)
        at org.mozilla.javascript.tools.shell.Main.processSource(Main.java:499)
        at org.mozilla.javascript.tools.shell.Main.processFiles(Main.java:215)
        at org.mozilla.javascript.tools.shell.Main$IProxy.run(Main.java:134)
        at org.mozilla.javascript.Context.call(Context.java:521)
        at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:535)
        at org.mozilla.javascript.tools.shell.Main.exec(Main.java:198)
        at org.mozilla.javascript.tools.shell.Main.main(Main.java:174)

Any comments would be appreciated. Thxs.

**Comment by eddyystop** [comment]
So I ran jsdoc in debug mode. (Yup,+1 to  NodeJS) The error is indeed 'Cannot find function get in Object'. 
    find: function(spec){
        return this.data.get( this.data.find(spec) );
    },

So taffy isn't doing its thing. Why? jsdoc.js in Main() has
taffy = require('taffydb').taffy,

In jsdoc.js around line 410 there's
 template.publish(
                taffy(docs),
                env.opts,
                resolver.root
            );

typeof taffy is a function, but taffy(docs).get is undefined at the call. So a config problem?

**Comment by eddyystop** [comment]
No mention on jsdoc github page about a taffy issue.

I did a refresh install of Jsdoc and myCustom. Same result.

Worth mentioning is I can run the default template fine. Though taffy(doc).get is undefined there too.

Any advice would be appreciated.

**Comment by eddyystop** [comment]
So I downloaded commit 8bc33541 of Jsdoc3 which is the last commit before changes started to be made for the Node port (+1) including some Taffy changes.

Got much, much further now. Crashing on 'System cannot find the path specified.' at ## genFilesPages. Likely something silly in the config.

Debugger shows its looking for ./inputsrc../package.json   Hmmm that ".." after my input folder is funny.

So I hacked rhino_modules/fs.js about line 8 adding
filename = filename.replace(/../g, '');

Then into my ./inputsrc I had to add
package.json from ./
LICENSE from ./LICENSE.MD though any file will do.
README with some junk.

Then I had to create a ./log folder. (Ah, that's where it goes.)

Then it ran. PROFIT!

Almost came up on browser.

**Comment by eddyystop** [comment]
(1) The HTML where the jsdoc3 (e.g. out) is written assumes a folder out/js containing
js/jquery-1.3.2.min.js
js/searchdoc.js

So you have to copy ./templates/myCustom/static/js to out/js
Whoops, all files within ./templates/myCustom/static are 0kb. 

What to do about searchdoc.js? Maybe author lists a sample site I can d/l from.

(2) index.html assumes you have class_index.html . That was not created as my input sample had no classes documented.

**Comment by joshrhoades** [comment]
I'm getting the same error and am stuck at the same `Cannot find function remove in object` error. I've gotten latest on everything, and did some of the same tweaks as outlined above, but am stick on this one. Nothing I've tried so far has worked. @eddyystop did you do anything specific to get around this? I know you got a refreshed build, but I got the latest from last week and its no go, where it sounds like you got an update and it worked fine (unless a subsequent release from when you got a fix went back and broke it).

**Comment by sadib** [comment]
Same error as @joshrhoades here. This is the log I get:

```
Init myPublisher
[DEBUG]  ## REMOVE OVER DATA ##
[DEBUG]  removing undocumented data
org.mozilla.javascript.EcmaError: TypeError: Cannot find function remove in object
function () {...}.
        at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3785)
        at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3763)
        at org.mozilla.javascript.ScriptRuntime.typeError(ScriptRuntime.java:3791)
        at org.mozilla.javascript.ScriptRuntime.typeError2(ScriptRuntime.java:3810)
        at org.mozilla.javascript.ScriptRuntime.notFunctionError(ScriptRuntime.java:3881)
        at org.mozilla.javascript.ScriptRuntime.getPropFunctionAndThisHelper(ScriptRuntime.java:2360)
        at org.mozilla.javascript.ScriptRuntime.getPropFunctionAndThis(ScriptRuntime.java:2327)
        at org.mozilla.javascript.gen.file__C__Users_sarah_Downloads_JSDoc3_jsdoc_master_templates_myCustom_inc_myPublisher_js_44._c_anonymous_4(Unknown Source)
        at org.mozilla.javascript.gen.file__C__Users_sarah_Downloads_JSDoc3_jsdoc_master_templates_myCustom_inc_myPublisher_js_44.call(Unknown Source)
        at org.mozilla.javascript.optimizer.OptRuntime.callProp0(OptRuntime.java:119)
        at org.mozilla.javascript.gen.file__C__Users_sarah_Downloads_JSDoc3_jsdoc_master_templates_myCustom_inc_myPublisher_js_44._c_anonymous_1(Unknown Source)
        at org.mozilla.javascript.gen.file__C__Users_sarah_Downloads_JSDoc3_jsdoc_master_templates_myCustom_inc_myPublisher_js_44.call(Unknown Source)
        at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:76)
        at org.mozilla.javascript.gen.file__C__Users_sarah_Downloads_JSDoc3_jsdoc_master_templates_myCustom_publish_js_43._c_anonymous_1(Unknown Source)
        at org.mozilla.javascript.gen.file__C__Users_sarah_Downloads_JSDoc3_jsdoc_master_templates_myCustom_publish_js_43.call(Unknown Source)
        at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:86)
        at org.mozilla.javascript.gen.C__Users_sarah_Downloads_JSDoc3_jsdoc_master_jsdoc_js_1._c_main_3(Unknown Source)
        at org.mozilla.javascript.gen.C__Users_sarah_Downloads_JSDoc3_jsdoc_master_jsdoc_js_1.call(Unknown Source)
        at org.mozilla.javascript.optimizer.OptRuntime.callName0(OptRuntime.java:108)
        at org.mozilla.javascript.gen.C__Users_sarah_Downloads_JSDoc3_jsdoc_master_jsdoc_js_1._c_script_0(Unknown Source)
        at org.mozilla.javascript.gen.C__Users_sarah_Downloads_JSDoc3_jsdoc_master_jsdoc_js_1.call(Unknown Source)
        at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:426)
        at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3178)
        at org.mozilla.javascript.gen.C__Users_sarah_Downloads_JSDoc3_jsdoc_master_jsdoc_js_1.call(Unknown Source)
        at org.mozilla.javascript.gen.C__Users_sarah_Downloads_JSDoc3_jsdoc_master_jsdoc_js_1.exec(Unknown Source)
        at org.mozilla.javascript.tools.shell.Main.evaluateScript(Main.java:654)
        at org.mozilla.javascript.tools.shell.Main.processFileSecure(Main.java:552)
        at org.mozilla.javascript.tools.shell.Main.processFile(Main.java:507)
        at org.mozilla.javascript.tools.shell.Main.processSource(Main.java:499)
        at org.mozilla.javascript.tools.shell.Main.processFiles(Main.java:215)
        at org.mozilla.javascript.tools.shell.Main$IProxy.run(Main.java:134)
        at org.mozilla.javascript.Context.call(Context.java:521)
        at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:535)
        at org.mozilla.javascript.tools.shell.Main.exec(Main.java:198)
        at org.mozilla.javascript.tools.shell.Main.main(Main.java:174)
```

**Comment by mbd-dbc-dk** [comment]
Hi there

I have updated the code to work with current JSDoc3. Please see this pull request:
https://github.com/danyg/jsdoc3Template/pull/6

**Comment by pooja0379** [comment]
I am getting error Error: Module "pajhome/hash" not found. I cant understand what is discussed above. Please give me some understandable solution.

**Comment by mbd-dbc-dk** [comment]
pooja0379 - until my changes are merged into this project, you can use this project instead:
https://github.com/DBCDK/jsdoc3Template
