### ISSUE TITLE
Java Exception with on JSDoc part

### ISSUE THREAD

**Issue by blackshadev** [danyg/jsdoc3Template#9]
I have pulled everything from your git (if it works, very nice work!).
I am on windows, used your batch file and changed the following:

```
REM jsdoc3\templates\%TEMPLATE%
SET TEMPLATE=nice

REM jsdoc3\doc\%OUTPUT_DIR%
SET OUTPUT_DIR=projects\Motor\docs\

REM jsdoc3\src\%INPUT_DIR%
SET INPUT_DIR=projects\Motor\src\

REM Working Copy, it's not be altered
SET ORIGINAL_SOURCE=C:\Users\dev\Dropbox\SrcDev\MotorDev\Motor
```

So I ran the batch and if jsdoc3 tries to run itselfs with your template file it crashes with the following exception (note: I also tried to ran this without the batch file, the same happend, except for the copy en clean part in the batch. )

```
JSDOC!
org.mozilla.javascript.WrappedException: Wrapped java.net.MalformedURLException:
 Illegal character in opaque part at index 2: C:\Users\dev\Documents\jsdoc3\temp
lates\nice\node_modules/
        at org.mozilla.javascript.Context.throwAsScriptRuntimeEx(Context.java:17
86)
        at org.mozilla.javascript.commonjs.module.Require.getModule(Require.java
:371)
        at org.mozilla.javascript.commonjs.module.Require.getExportedModuleInter
face(Require.java:260)
        at org.mozilla.javascript.commonjs.module.Require.call(Require.java:214)

        at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:
97)
        at org.mozilla.javascript.gen.file__C__Users_dev_Documents_jsdoc3_templa
tes_nice_publish_js_44._c_anonymous_1(Unknown Source)
        at org.mozilla.javascript.gen.file__C__Users_dev_Documents_jsdoc3_templa
tes_nice_publish_js_44.call(Unknown Source)
        at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:86)

        at org.mozilla.javascript.gen.C__Users_dev_Documents_jsdoc3_jsdoc_js_1._
c_main_3(Unknown Source)
        at org.mozilla.javascript.gen.C__Users_dev_Documents_jsdoc3_jsdoc_js_1.c
all(Unknown Source)
        at org.mozilla.javascript.optimizer.OptRuntime.callName0(OptRuntime.java
:108)
        at org.mozilla.javascript.gen.C__Users_dev_Documents_jsdoc3_jsdoc_js_1._
c_script_0(Unknown Source)
        at org.mozilla.javascript.gen.C__Users_dev_Documents_jsdoc3_jsdoc_js_1.c
all(Unknown Source)
        at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:4
26)
        at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:317
8)
        at org.mozilla.javascript.gen.C__Users_dev_Documents_jsdoc3_jsdoc_js_1.c
all(Unknown Source)
        at org.mozilla.javascript.gen.C__Users_dev_Documents_jsdoc3_jsdoc_js_1.e
xec(Unknown Source)
        at org.mozilla.javascript.tools.shell.Main.evaluateScript(Main.java:654)

        at org.mozilla.javascript.tools.shell.Main.processFileSecure(Main.java:5
52)
        at org.mozilla.javascript.tools.shell.Main.processFile(Main.java:507)
        at org.mozilla.javascript.tools.shell.Main.processSource(Main.java:499)
        at org.mozilla.javascript.tools.shell.Main.processFiles(Main.java:215)
        at org.mozilla.javascript.tools.shell.Main$IProxy.run(Main.java:134)
        at org.mozilla.javascript.Context.call(Context.java:521)
        at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:535)
        at org.mozilla.javascript.tools.shell.Main.exec(Main.java:198)
        at org.mozilla.javascript.tools.shell.Main.main(Main.java:174)
Caused by: java.net.MalformedURLException: Illegal character in opaque part at i
ndex 2: C:\Users\dev\Documents\jsdoc3\templates\nice\node_modules/
        at org.mozilla.javascript.commonjs.module.provider.ModuleSourceProviderB
ase.loadFromPathArray(ModuleSourceProviderBase.java:81)
        at org.mozilla.javascript.commonjs.module.provider.ModuleSourceProviderB
ase.loadSource(ModuleSourceProviderBase.java:43)
        at org.mozilla.javascript.commonjs.module.provider.CachingModuleScriptPr
oviderBase.getModuleScript(CachingModuleScriptProviderBase.java:65)
        at org.mozilla.javascript.commonjs.module.provider.SoftCachingModuleScri
ptProvider.getModuleScript(SoftCachingModuleScriptProvider.java:63)
        at org.mozilla.javascript.commonjs.module.Require.getModule(Require.java
:359)
        ... 25 more
```

I think the slash used at the end of the path is the wrong way for Windows.

I hope you can fix this. Or if you can tell me what I did wrong and can do to make it work.

With kind regards,
Vincent

**Comment by mbd-dbc-dk** [comment]
Hi there

I am on Linux, so not much help here.

Perhaps danyg can solve this, but just wanted to add that I have had troubles getting the template to work, if it was called something other than myCustom (your have put yours in "nice", it seems). This is not related to your error, I think, because it seems to fail very early.

What is your working directory - where do you run this script from?

Also, what is your version of jsdoc? How did you install it?

**Comment by danyg** [comment]
I think is a trouble in the Rhino flavored require, it's not work like in node.js, I put a issue in the customized rhino for jsdoc3.

https://github.com/hegemonic/rhino/issues/1

I will be a branch to work with Windows until hegemonic resolve the issue.

**Comment by danyg** [comment]
Ok, I've looked more deeply, and I found a solution in Windows, resolved at commit e2721dc711

**Comment by blackshadev** [comment]
Hi, thanks for the fast reply.

I am running JSDoc3.1.0 from C:\Users\Username\Documents\jsdoc.

It could be a problem with the foldername, I will check that this week and
I will you know.
Let me know if you find anything.

regards,
Vincent

**Comment by blackshadev** [comment]
Thanks,

I will try it and I will let you know ;)

**Comment by blackshadev** [comment]
It works! Thank you for the fast reply and sorry for my late reaction.
Great tool, allot better than the normal skin.

May I propose something? Can you make (if it is not already in it) addition
searchable tags.
I want to add more searchable tags/lines to my documentation, or if it is
posible, make the description searchable.

Vincent

**Comment by danyg** [comment]
Thank you for use this template.
About the search, I think that can be maded. Please create an Issue explaining the complete functionality that you want and tag them how improvement.
